COLLECTION_NAME = "company_intel"
DENSE_VECTOR_NAME = "dense"
SPARSE_VECTOR_NAME = "sparse"
DENSE_DIM = 384
UPSERT_BATCH_SIZE = 100

SEARCH_DENSE_LIMIT = 10
SEARCH_SPARSE_LIMIT = 10
SEARCH_FUSION_LIMIT = 5
DENSE_SCORE_THRESHOLD = 0.45
CONTEXT_BUDGET_TOKENS = 3000
